
package aleatorio;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author 50enta
 */
public class Tela extends javax.swing.JFrame {

    ArrayList<Integer> restricoes;
    ArrayList<Label> labels;

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        restricoes = new ArrayList<>();
        labels = new ArrayList<>();
        jspnValMax.setValue(15);
        this.adicionarPaineis();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        lblResult = new javax.swing.JLabel();
        painelOk = new javax.swing.JPanel();
        lblOk = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jspnValMax = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        pnlBase = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Qual será o próximo grupo?");
        setResizable(false);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lblResult.setFont(new java.awt.Font("Tahoma", 1, 330)); // NOI18N
        lblResult.setText(" ??");

        painelOk.setBackground(new java.awt.Color(255, 255, 255));
        painelOk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lblOk.setBackground(new java.awt.Color(255, 255, 255));
        lblOk.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblOk.setText("   QualSerá?");
        lblOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOkMouseExited(evt);
            }
        });

        javax.swing.GroupLayout painelOkLayout = new javax.swing.GroupLayout(painelOk);
        painelOk.setLayout(painelOkLayout);
        painelOkLayout.setHorizontalGroup(
            painelOkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblOk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
        );
        painelOkLayout.setVerticalGroup(
            painelOkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblOk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(painelOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 368, Short.MAX_VALUE)
                .addGap(52, 52, 52)
                .addComponent(painelOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("Sorteio", jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));

        jspnValMax.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jspnValMaxStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Total de grupos");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(413, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jspnValMax, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jspnValMax, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel9.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        pnlBase.setBackground(new java.awt.Color(255, 255, 255));
        pnlBase.setLayout(new java.awt.BorderLayout());
        jPanel9.add(pnlBase, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel9, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Restrições", jPanel5);

        jPanel3.add(jTabbedPane1, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOkMouseClicked
        // TODO add your handling code here:
        this.aoclicar();
    }//GEN-LAST:event_lblOkMouseClicked

    private void jspnValMaxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jspnValMaxStateChanged
        // TODO add your handling code here:
        this.pnlBase.removeAll();
        this.pnlBase.repaint();
        this.pnlBase.add(this.adicionarPaineis());
        this.pnlBase.revalidate();
    }//GEN-LAST:event_jspnValMaxStateChanged

    private void lblOkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOkMouseEntered
//        painelOk.setBackground(Color.black);
//        lblOk.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblOkMouseEntered

    private void lblOkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOkMouseExited
//        painelOk.setBackground(Color.WHITE);
//        lblOk.setForeground(Color.black);
    }//GEN-LAST:event_lblOkMouseExited

    public void aoclicar() {
        int max = (int) jspnValMax.getValue();

        if (max <= 0 || max >= 20) {
            JOptionPane.showMessageDialog(null, "Introduza valores entre [1 - 20]");
        } else {
            lblResult.setText("::::");
            Calcular bgc = new Calcular(max, lblResult, calcularRestricoes());
            bgc.execute();
        }
    }

    private Component adicionarPaineis() {
        int max = (int) jspnValMax.getValue();
        JPanel a = new JPanel();
        a.setLayout(new GridLayout(5, 3));
        a.setBackground(Color.WHITE);
        for (int i = 1; i <= max; i++) {
            JPanel b = new JPanel();
            b.setBackground(Color.WHITE);
            Label img = new Label("not01.png", i);
            labels.add(img);
            b.add(img);
            JLabel text = new JLabel((i < 10) ? "0" + i : Integer.toString(i));
            text.setFont(new Font(Font.SANS_SERIF, Font.BOLD, 43));
            b.add(text);
            a.add(b);
        }
        return new JScrollPane(a);
    }

    public ArrayList<Integer> calcularRestricoes() {
        ArrayList<Integer> nums = new ArrayList<>();
        for (Label a : this.labels) {
            if (a.isVerdade()) {
                nums.add(a.getNumero());
            }
        }
        return nums;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner jspnValMax;
    private javax.swing.JLabel lblOk;
    private javax.swing.JLabel lblResult;
    private javax.swing.JPanel painelOk;
    private javax.swing.JPanel pnlBase;
    // End of variables declaration//GEN-END:variables
}
